#!/bin/bash
# 001_databases.sh — runs once on first PG startup (docker-entrypoint-initdb.d).
# Creates the shared instance's app roles and databases. Idempotent.
# The kernel schema (six tables + triggers) is NOT defined here: it ships with
# the kernel repo (ops/sql/0001_init.sql) and is applied by migrations from CI.
# Passwords are hex strings generated by bootstrap.sh (no quoting hazards).
set -euo pipefail

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<EOSQL
DO \$\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'kernel') THEN
        CREATE ROLE kernel LOGIN PASSWORD '${KERNEL_PG_PASSWORD}';
    END IF;
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'litellm') THEN
        CREATE ROLE litellm LOGIN PASSWORD '${LITELLM_PG_PASSWORD}';
    END IF;
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'langfuse') THEN
        CREATE ROLE langfuse LOGIN PASSWORD '${LANGFUSE_PG_PASSWORD}';
    END IF;
END
\$\$;
SELECT 'CREATE DATABASE litellm OWNER litellm'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'litellm')\gexec
SELECT 'CREATE DATABASE langfuse OWNER langfuse'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'langfuse')\gexec
SELECT 'CREATE DATABASE company OWNER kernel'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'company')\gexec
EOSQL
